services:
  traefik:
    image: traefik:2.8
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.routers.traefik.service=api@internal"

  todo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
      - "traefik.http.routers.todo.tls=true"
      - "traefik.http.routers.todo.rule=Host(`todo.tradesync.software`)"
      - "traefik.http.routers.todo.entrypoints=websecure"
      - "traefik.http.routers.todo.tls.certresolver=letsencrypt"
      - "traefik.http.routers.todo.service=todo"
      - "traefik.http.services.todo.loadbalancer.server.port=8000"

  database:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    networks:
      - proxy
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

networks:
  proxy:
    external: true

volumes:
  media_volume:
  static_volume:
  database:
  app:
