services:
  traefik:
    image: traefik:2.8
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik.service=traefik"
      - "traefik.http.routers.traefik.service=api@internal"

  todo:
    build: .
    container_name: todo
    restart: always
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.todo.tls=true"
      - "traefik.http.routers.todo.rule=Host(`todo.tradesync.software`)"
      - "traefik.http.routers.todo.entrypoints=websecure"
      - "traefik.http.services.todo.loadbalancer.server.port=8000"
      - "traefik.http.routers.todo.tls.certresolver=letsencrypt"  

networks:
  proxy:
    external: true
    name: proxy