services:
  traefik:
    image: traefik:2.8
    container_name: traefik
    restart: unless-stopped
    networks:
      - public_net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - "./acme.json:/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=public_net"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.todo.tradesync.software`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

  todo:
    build: .
    container_name: todo
    restart: always
    volumes:
      - ./db:/app/db
    env_file:
      - .env
    networks:
      - public_net
      - private_net
    ports:
      - "8000:8000"
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public_net"
      - "traefik.http.routers.todo-http.rule=Host(`todo.tradesync.software`)"
      - "traefik.http.routers.todo-http.entrypoints=web"
      - "traefik.http.routers.todo.rule=Host(`todo.tradesync.software`)"
      - "traefik.http.routers.todo.entrypoints=websecure"
      - "traefik.http.routers.todo.tls=true"
      - "traefik.http.routers.todo.tls.certresolver=letsencrypt"
      - "traefik.http.services.todo.loadbalancer.server.port=8000"

  database:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - private_net

networks:
  public_net:
    external: true
  private_net:
    external: true

volumes:
  postgres_data: