api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: jastinlasway10@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: websecure
# Ensure the entryPoint matches the secure route
